batch_nums_per_epoch: 10000
defaults: null
feature_dims: 64
fix_len: 3
hop_length: 512
lr: 1.0e-05
max_step: 100
model_name: sinc-ge2e
n_fft: 512
n_gpu: 1
n_speaker: 1840
n_speaker_test: 151
n_threads: 6
num_classes_per_batch: 16
num_utt_per_class: 4
sample_rate: 16000
save_path: /home/fhq/save/sinc-ge2e
slides:
- 0
- 0
